### ISSUE TITLE
Addon not loading

### ISSUE THREAD

**Issue by DeSavanger** [itz-coffee/discord-relay#3]
Hi,

It seems like the addon is just not loading, while it's in my addons folder... It says that the addon is mounted in the console.log, but I can't see something like "Connected to websocket server" or "Websocket error:" in my console.log....

**Comment by DeSavanger** [comment]
It works. I had to make sure the addons/DiscordRelay folder was renamed to addons/discordrelay
The only problem I have now, is that there's no Steam avatar from the player showing up in the Discord-server... Everything else works.

**Comment by DeSavanger** [comment]
I fixed it. Your avatar URL's are wrong.

In `addons/DiscordRelay/lua/autorun/server/sv_discord_relay.lua`, change
```local link = body:match("https://cdn.akamai.steamstatic.com/steamcommunity/public/images/avatars/.-jpg")```
to
```local link = body:match("https://avatars.cloudflare.steamstatic.com/.-jpg")```

In `web/src/app.ts`, change
```avatar?: `https://cdn.akamai.steamstatic.com/steamcommunity/public/images/avatars/${number}_full.jpg`,```
to
```avatar?: `https://avatars.cloudflare.steamstatic.com/${number}_full.jpg`,```

**Comment by itz-coffee** [comment]
Sorry for the late reply, @VottonDev fixed it with their PR
