### ISSUE TITLE
Typo after recent commit

### ISSUE THREAD

**Issue by DeSavanger** [itz-coffee/discord-relay#6]
Hi,

I think you mistyped something after your recent commit (#5).
In **\garrysmod\addons\discordrelay\lua\autorun\server\sv_discord_relay.lua** on line **#56**, I think you need to change `fetchedavatars[client:SteamID64()]`
to
`fetchedavatars[client:SteamID64()] = nil`
otherwise the script is not loading and the console throws an error.

**Comment by DeSavanger** [comment]
Ok, it's completely broken now. The bot doesn't print any text in the Discord chat text channel... It does print the Discord text chats in the Garry's Mod server, though... It also still prints: "**Connected to websocket server**" in **console.log**.
Did you test the script after commit #5?

**Comment by DeSavanger** [comment]
Hmm, it seems that everytime I'm saying something in my Gmod chat, I get this message:
"**Websocket disconnected, retrying...
Connected to websocket server**"

Also, I don't know where I can find the logs from the websocket bot...

**Comment by itz-coffee** [comment]
> Hi,
> 
> I think you mistyped something after your recent commit (#5). In **\garrysmod\addons\discordrelay\lua\autorun\server\sv_discord_relay.lua** on line **#56**, I think you need to change `fetchedavatars[client:SteamID64()]` to `fetchedavatars[client:SteamID64()] = nil` otherwise the script is not loading and the console throws an error.

I did not as I've worked with this contributor before, I've removed the hook altogether and it should work again, sorry about that

**Comment by itz-coffee** [comment]
> Hmm, it seems that everytime I'm saying something in my Gmod chat, I get this message: "**Websocket disconnected, retrying... Connected to websocket server**"
> 
> Also, I don't know where I can find the logs from the websocket bot...

I think I had this issue when I didn't have my firewall setup right on my server. Could be related? Make sure the port is open

**Comment by DeSavanger** [comment]
> > Hi,
> > I think you mistyped something after your recent commit (#5). In **\garrysmod\addons\discordrelay\lua\autorun\server\sv_discord_relay.lua** on line **#56**, I think you need to change `fetchedavatars[client:SteamID64()]` to `fetchedavatars[client:SteamID64()] = nil` otherwise the script is not loading and the console throws an error.
> 
> I did not as I've worked with this contributor before, I've removed the hook altogether and it should work again, sorry about that

It still doesn't work. It does work when I'm texting something in my Discord chat, then I'm able to see it in Gmod. But, when I text something in Gmod, I cannot see it in my Discord channel anymore...

**Comment by DeSavanger** [comment]
> > Hmm, it seems that everytime I'm saying something in my Gmod chat, I get this message: "**Websocket disconnected, retrying... Connected to websocket server**"
> > Also, I don't know where I can find the logs from the websocket bot...
> 
> I think I had this issue when I didn't have my firewall setup right on my server. Could be related? Make sure the port is open

Port is open...

**Comment by DeSavanger** [comment]
It's doing this always whenever I type some text in Gmod, that he needs to send to Discord:

> ServerLog: "WhiteSasch<11><STEAM_0:0:37471628><Citizen>" say "/ooc test"
> Websocket disconnected, retrying...
> Connected to websocket server

**Comment by itz-coffee** [comment]
Ok, I'll take a look today when I'm at my PC. If you have any more information or a fix let me know

**Comment by DeSavanger** [comment]
> Ok, I'll take a look today when I'm at my PC. If you have any more information or a fix let me know

If you want, we can discuss together on Discord about the fixes?

**Comment by DeSavanger** [comment]
Hi, did you already have time to look at it? It's still the same issue...

**Comment by itz-coffee** [comment]
Feeling a little sick not sure when I can be able to properly debug this, hopefully soon-ish

**Comment by DeSavanger** [comment]
Ok...

**Comment by DeSavanger** [comment]
I guess I'll seek another addon.
